package:
  name: scotch
  version: "6.0.4"

source:
  fn: scotch_6.0.4.tar.gz
  url: http://gforge.inria.fr/frs/download.php/file/34618/scotch_6.0.4.tar.gz
  md5: d58b825eb95e1db77efe8c6ff42d329f
  patches:
    - clock_gettime.patch [osx]

build:
  number: 1

about:
  home: http://www.labri.fr/perso/pelegrin/scotch/
  license: CeCILL-C
